# Generated by Django 4.1.5 on 2023-01-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
        migrations.RenameModel(
            old_name="Managers",
            new_name="Manager",
        ),
        migrations.RenameModel(
            old_name="Sermons",
            new_name="Sermon",
        ),
        migrations.RenameModel(
            old_name="Subscribers",
            new_name="Subscriber",
        ),
    ]
