# Generated by Django 4.1.5 on 2023-01-25 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_events_event_rename_managers_manager_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="event_time",
        ),
    ]
