# Generated by Django 4.1.5 on 2023-01-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_remove_event_event_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sermon",
            name="name",
        ),
        migrations.AddField(
            model_name="sermon",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="sermon",
            name="audio_link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="date",
            field=models.DateField(null=True, verbose_name="Event Date"),
        ),
        migrations.AddField(
            model_name="sermon",
            name="speaker",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="sermon",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
