# Generated by Django 4.1.5 on 2023-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_remove_sermon_name_sermon_audio_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="speaker",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="title",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
