# Generated by Django 4.1.5 on 2023-01-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_sermon_speaker_alter_sermon_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="date",
            field=models.DateTimeField(null=True, verbose_name="Event Date"),
        ),
    ]
