# Generated by Django 4.1.5 on 2023-01-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_alter_sermon_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sermon",
            name="audio_link",
        ),
    ]
