# Generated by Django 4.1.5 on 2023-01-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_remove_sermon_audio_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="media/sermons/"),
        ),
    ]
