# Generated by Django 4.1.5 on 2023-01-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_sermon_audio_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sermon",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
