# Generated by Django 4.1.5 on 2023-02-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_event_manager_alter_sermon_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_time",
            field=models.TimeField(null=True, verbose_name="Event Time"),
        ),
        migrations.AddField(
            model_name="sermon",
            name="time",
            field=models.CharField(max_length=4, null=True, verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateTimeField(null=True, verbose_name="Event Date"),
        ),
        migrations.AlterField(
            model_name="sermon",
            name="date",
            field=models.DateField(null=True, verbose_name="Date"),
        ),
    ]
