# Generated by Django 4.1.5 on 2023-02-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0012_event_event_time_sermon_time_alter_event_event_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(null=True, verbose_name="Event Date"),
        ),
    ]
