# Generated by Django 4.1.7 on 2023-03-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_alter_event_event_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="manager",
        ),
        migrations.DeleteModel(
            name="Manager",
        ),
        migrations.DeleteModel(
            name="Subscriber",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
    ]
